### ISSUE TITLE
Android Build Issue

### ISSUE THREAD

**Issue by tajari** [square/in-app-payments-react-native-plugin#10]
When I added in-app-payments-react-native-plugin into my project, I can no longer build the android version. I configured everything and still can't build it

Here is the log

:react-native-version-number:generateReleaseRFile
:app:processStagingreleaseResources/Users/vagrant/.gradle/caches/transforms-1/files-1.1/card-entry-1.1.0.aar/195da94f45eab2bc350b9432461672e5/res/layout/sqip_activity_card_entry.xml:26:44-59: AAPT: No resource found that matches the given name (at 'layout_constraintBottom_toTopOf' with value '@id/save_button')

  Steps to reproduce the issue.

  1. add module to your project
  2. run react-native run-android

Config :

    buildToolsVersion = "28.0.2"
    minSdkVersion = 21
    compileSdkVersion = 27
    targetSdkVersion = 27
    supportLibVersion = "27.1.1"
    sqipVersion="1.1.0"

Env : 
 - Platform : Android
 - dev env : MacOS
 - in app payment version : 1.1.2

Environment : 
  - platform: [e.g. iOS or Android]
  - OS and version: [e.g. iOS8.1]
  - dev environment: [e.g. MacOS or Windows]
  - In-App Payments Plugin version: [e.g. 1.1.1]

  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 26.89 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

I think one of module files has some bug. In the file 'sqip_activity_card_entry.xml' these lines should change :

Line 26 :
Original            : app:layout_constraintBottom_toTopOf="@id/save_button"
It should change to : app:layout_constraintBottom_toTopOf="@+id/save_button"

Line 67 :
Original            : android:id="@+id/save_button"
It should change to : android:id="@id/save_button"

**Comment by StephenJosey** [comment]
Thanks for reporting this! We've seen this before and we're currently working on a fix for it. As far as we know, there's currently not a workaround, so we're trying our best to get this out in a timely manner. We'll update this thread as soon as we have more information.

**Comment by StephenJosey** [comment]
This was resolved.
