### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by LukhiKartik** [square/in-app-payments-react-native-plugin#103]
### Describe the issue
  Can not able to create android build

### Screenshots
<img width="715" alt="Screenshot 2021-04-14 at 5 02 03 PM" src="https://user-images.githubusercontent.com/43737760/114704259-07417780-9d44-11eb-8156-8e8f85520746.png">
  
  Here is the log:
  '''
 > Task :app:checkReleaseDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.JWEObject$State found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.JWSObject found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.JWSObject$State found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.Payload found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.Payload$Origin found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.Requirement found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter$AlgFamily found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.crypto.impl.ECDH$AlgorithmMode found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)
  Duplicate class com.nimbusds.jose.jwk.KeyOperation found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-7.8.jar (com.nimbusds:nimbus-jose-jwt:7.8)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 50s
401 actionable tasks: 367 executed, 34 up-to-date

  ```
-->

### To Reproduce
<!--
  Steps to reproduce the issue.

  For example - 
  1. ./gradlew clean - clean successful
  2. ./gradlwe assembleRelease - build failed


**Environment (please complete the following information):**
<!--
  - platform: Android

-->


### Additional context
gradle-wrapper.properties

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists


build.gradle

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        sqipVersion="1.4.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}



gradle.properties

android.useAndroidX=true
android.enableJetifier=true
android.enableR8 = false



package.json

"dependencies": {
    "@invertase/react-native-apple-authentication": "^1.1.1",
    "@react-native-community/async-storage": "1.7.1",
    "@react-native-community/cli-platform-android": "3.0.2",
    "@react-native-community/geolocation": "2.0.2",
    "@react-native-community/masked-view": "0.1.6",
    "@react-native-community/netinfo": "5.3.3",
    "@react-native-community/viewpager": "3.3.0",
    "axios": "0.19.2",
    "currency-symbol-map": "^4.0.4",
    "intl": "^1.2.5",
    "moment": "2.24.0",
    "moment-timezone": "^0.5.33",
    "prop-types": "15.7.2",
    "radio-buttons-react-native": "^1.0.4",
    "react": "16.9.0",
    "react-intl": "^5.10.6",
    "react-native": "0.61.5",
    "react-native-android-location-enabler": "1.2.0",
    "react-native-check-box": "2.1.7",
    "react-native-collapsible": "1.5.1",
    "react-native-device-info": "5.5.3",
    "react-native-dropdownalert": "4.2.1",
    "react-native-fbsdk": "1.1.1",
    "react-native-firebase": "5.6.0",
    "react-native-gesture-handler": "1.7.0",
    "react-native-google-places": "3.1.2",
    "react-native-google-signin": "2.1.1",
    "react-native-image-crop-picker": "0.25.0",
    "react-native-image-progress": "^1.1.1",
    "react-native-iphone-x-helper": "1.2.1",
    "react-native-keyboard-aware-scroll-view": "0.9.1",
    "react-native-keychain": "^6.1.1",
    "react-native-linear-gradient": "2.5.6",
    "react-native-material-dropdown": "0.11.1",
    "react-native-material-textfield": "0.16.1",
    "react-native-permissions": "2.0.9",
    "react-native-picker-scrollview": "^1.0.1",
    "react-native-reanimated": "1.7.0",
    "react-native-safe-area-context": "0.6.2",
    "react-native-screens": "^2.11.0",
    "react-native-snap-carousel": "3.8.4",
    "react-native-splash-screen": "3.2.0",
    "react-native-square-in-app-payments": "^1.4.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-webview": "8.0.6",
    "react-navigation": "4.0.10",
    "react-navigation-stack": "2.0.16",
    "react-navigation-tabs": "2.7.0",
    "react-redux": "7.1.3",
    "redux": "4.0.5",
    "redux-thunk": "2.3.0",
    "tipsi-stripe": "8.0.0-beta.9"
  },

**Comment by StephenJosey** [comment]
Thanks for sharing, the team will take a look at this.

**Comment by LukhiKartik** [comment]
Any update?

**Comment by vatsal-gadhiya-searce** [comment]
@StephenJosey Can you guys help here. As we have promised delivery this month. The development is done but the build is failing for android. We have gone through the issues over internet but no luck. Happy to try whatever you guys suggest.

**Comment by LukhiKartik** [comment]
@StephenJosey  Any update?

**Comment by LukhiKartik** [comment]
This one works fine for me. https://github.com/square/in-app-payments-react-native-plugin/issues/62#issuecomment-627163091
