### ISSUE TITLE
SCA card-on-file implementation

### ISSUE THREAD

**Issue by darajava** [square/in-app-payments-react-native-plugin#106]
We are currently using saved cards in our system, and charging our users when it's appropriate to do so. We have a basic flow (take card details in react native plugin, save card in square, and charge with our backend at a later time).

SCA is coming into effect and will be mandatory soon. There are guides for using it for android and ios (native) but none for the react native plugin. Is there anything we need to do to supposed SCA? Will it be taken care of automatically?

**Comment by StephenJosey** [comment]
There's existing functionality for verifying the buyer for SCA in this plugin already: https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/reference.md#startcardentryflowwithbuyerverification. With that said, there is an open PR (https://github.com/square/in-app-payments-react-native-plugin/pull/104) as well that is adding the verification flow for card on file.

**Comment by vishwajitshep0815** [comment]
This feature is implemented in the latest releases. So, closing the issue.
