### ISSUE TITLE
tutorial/example immediately crashes after launching in android emulator

### ISSUE THREAD

**Issue by AnachronicNomad** [square/in-app-payments-react-native-plugin#118]
### Describe the issue

Running the tutorial immediately crashes after load with no logs provided.  

### To Reproduce

1. Create a device in AVDManager with your choice of API 28-30. 
2. Run said device.
3. Follow the steps described in the tutorial, including `react-native start` and `react-native run-android --deviceId='<YOUR_DEV_ID>'` to use the specific device.
4. Scream and pull out a chunk of hair because your friend's startup is probably going to go under from paying out 80% to Authorize.net, you've tried about 7-8 different Payment SDKs at this point built for both Stripe and Square none of which actually work, then curse the person who advocated for said SDKs instead of just allowing a POST to submit card details to get the card nonce. 

### Expected behavior

The default tutorial _just runs_. 

**Environment (please complete the following information):**

  - platform: **Android**
  - OS and version: **API 28-30**
  - dev environment: **Ubuntu**
  - In-App Payments Plugin version: **Attached is `yarn.lock` https://pastebin.com/N4eAv18U and `package.json` https://pastebin.com/buYbmjYg** 

  In addition: Run `react-native info` in your terminal and copy the results here.

```
info Fetching system and libraries information...
System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 3.28 GB / 30.80 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.11.0 - /usr/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

### Additional context

Seriously you should allow your Payments API to just accept a POST request to generate a nonce for given card info.  The fact it's not available anymore is atrocious.

**Comment by StephenJosey** [comment]
Hi @AnachronicNomad sorry to hear it's not working. To confirm, you're not seeing any errors in your command terminal nor on the emulator itself? I just tested on a Pixel 4 emulation (API 30), and was able to install and launch it successfully.

To add, we do not allow POSTing of raw card data to our endpoints, as that increases risk to the card data itself, and it would require all development applications to be PCI Compliant, rather than just relying on Square's PCI Compliance. It is a feature request that gets brought up occasionally, though, and I'll be sure to pass it on to the correct folks.

**Comment by AnachronicNomad** [comment]
@StephenJosey Thanks, yes that was correct.  I will try to free up some time tonight to rebuild, rerun, and record a video, maybe that will be more helpful.

**Comment by AnachronicNomad** [comment]
@StephenJosey Here is a video capture (after the list) of my attempt to get the react-native example running, in an absolutely bare environment, after reinstalling `android-studio` and everything else, using `API 30`.  Unfortunately audio capture did not work on my end, and I don't have time to re-record (it's 4:12 am my time) -- **be warned, the audio splits back in absurdly loud at 10:32, make sure to turn down your volume**.  Some key things that should stand out:   

1. The README.md documentation should **not** tell users to empty out the `./node-modules` folder.  This causes dependency conflicts between `yarn` and actually running the emulator as is now required with `$ npx react-native run-android`.   
2. Opening the project in the newest version of Android Studio (with Gradle v7) fails due to behavior reliant on Gradle 6.5 or something.  
3. The app appears to fail upon initializing the SquareProvider environment.  I deleted/lost the bare-minimum sample code I copied from the Payments SDK API docs at connect.squareup.com or whatever, but the same behavior is observed; a crash immediately after launch with an error of "App keeps stopping".

**Comment by AnachronicNomad** [comment]
Follow up:  Just tried a clean build with API 27 (as recommended in the `README`), and this crashes as well in the same manner. 
https://imgur.com/bLHwa6M

**Comment by AnachronicNomad** [comment]
Follow up 3:  Actually @StephenJosey I just want to say that submitting card info is even more than people like myself really need -- it would be absolutely sick if I could POST a charge amount to an API endpoint which gives me a Square-hosted checkout/cart landing page that I can directly open in the users' mobile browser.  That way I could go completely serverless and further reduce some of the overhead (we don't need a server for...almost anything).

**Comment by CharmisG** [comment]
@AnachronicNomad Can you please try again now it's resolved in latest update.
