### ISSUE TITLE
ZIP to Postcode localization not working

### ISSUE THREAD

**Issue by tinymobile** [square/in-app-payments-react-native-plugin#123]
Hi.  

I've updated the react native plug in for Square and it's now putting ZIP instead of POSTCODE in the card entry form. In a previous version, I had to add the localisation to Xcode to modify this for a UK app:

https://developer.squareup.com/docs/in-app-payments/localize-ios

But now this isn't working. When I add the localisation to Xcode, it is saying '0 Files Localized', whereas on my earlier version, it was saying '1 Files Localized'. In the app itself, it then says ZIP regardless of the test cards I use and my system language setup on device.

I've attached the earlier version and the latest version to show the difference.

<img width="689" alt="earlierversion" src="https://user-images.githubusercontent.com/45669511/123969987-a58ec200-d9b0-11eb-99c7-dc2d3e0c8a9b.png">
<img width="702" alt="currentversion" src="https://user-images.githubusercontent.com/45669511/123969993-a6bfef00-d9b0-11eb-9656-3d09b9e7779f.png">

**Comment by PeterOla** [comment]
Hi, Did you find a solution to this?

**Comment by tinymobile** [comment]
Hi No,

I’ve upgraded to Xcode 13 and built a new project, and the instructions still do not work.

https://developer.squareup.com/docs/in-app-payments/localize-ios

Any Ideas Square?

Paul

**Comment by CharmisG** [comment]
Closing this issue but if you still find this problem please reopen this issue. Thank you.
