### ISSUE TITLE
Square Secure Authentication in Dark Mode

### ISSUE THREAD

**Issue by tinymobile** [square/in-app-payments-react-native-plugin#125]
I'm having a problem with the Square Secure Authentication UX in the React Native SCA implementation.  If the test phone is set to 'Dark Mode' then the text and input box is missing (see first screenshot attached).  If I set it to Light Mode, then it works (as per the second screenshot). 

To reproduce, call startCardEntryFlowWithBuyerVerification from within the app on a device that is set to Dark Mode and enter one of the test cards that prompts SCA authentication.

![Image from iOS (43) (43)](https://user-images.githubusercontent.com/45669511/123971582-197d9a00-d9b2-11eb-928d-642f45374f46.png)
![Image from iOS (42) (42)](https://user-images.githubusercontent.com/45669511/123971594-1aaec700-d9b2-11eb-8ac2-43d2b2a2e6f3.png)

**Comment by CharmisG** [comment]
@tinymobile 
This is just plugin so we haven't implement it in dark mode currently it's only for light mode.
Sorry for in inconvenience !!
