### ISSUE TITLE
ios platform version

### ISSUE THREAD

**Issue by n3rd253** [square/in-app-payments-react-native-plugin#126]
### Describe the issue
I just installed the plugin and went to pod install, my platform ios version is already set to 11.

But when I pod install I get 

`[!] CocoaPods could not find compatible versions for pod "RNSquareInAppPayments":
  In Podfile:
    RNSquareInAppPayments (from `../node_modules/react-native-square-in-app-payments`)

Specs satisfying the `RNSquareInAppPayments (from `../node_modules/react-native-square-in-app-payments`)` dependency were found, but they required a higher minimum deployment target.`

### Expected behavior
The pods install

**Environment (please complete the following information):**

  - platform: iOS
  - OS and version: iOS11
  - dev environment: MacOS
  - In-App Payments Plugin version: ^1.5.0

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 55.87 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by n3rd253** [comment]
@StephenJosey any idea here?  Changing to 12.0 worked.  Is the documentation wrong?

**Comment by jguze** [comment]
This looks fixed with PR #127
