### ISSUE TITLE
iOS debug/release build fails with use_frameworks xcode 12.4

### ISSUE THREAD

**Issue by saifuddinpopcornapps** [square/in-app-payments-react-native-plugin#138]
### Here is the log:

Cycle in dependencies between targets 'RNSquareTestApp' and 'FBReactNativeSpec'; building could produce unreliable results.
Cycle path: RNSquareTestApp → FBReactNativeSpec → RNSquareTestApp
Cycle details:
→ Target 'RNSquareTestApp': CodeSign /Users/apple/Library/Developer/Xcode/DerivedData/RNSquareTestApp-aadaupixwpzapzggbgqqyasftnbc/Build/Products/Debug-iphonesimulator/RNSquareTestApp.app
○ Target 'RNSquareTestApp': ProcessProductPackaging  /Users/apple/Library/Developer/Xcode/DerivedData/RNSquareTestApp-aadaupixwpzapzggbgqqyasftnbc/Build/Intermediates.noindex/RNSquareTestApp.build/Debug-iphonesimulator/RNSquareTestApp.build/RNSquareTestApp.app.xcent
○ Target 'RNSquareTestApp' has target dependency on Target 'FBReactNativeSpec'
○ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”
→ Target 'FBReactNativeSpec' has copy command from '/Users/apple/Documents/Saif/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec.h' to '/Users/apple/Library/Developer/Xcode/DerivedData/RNSquareTestApp-aadaupixwpzapzggbgqqyasftnbc/Build/Products/Debug-iphonesimulator/FBReactNativeSpec/FBReactNativeSpec.framework/Headers/FBReactNativeSpec.h'
○ That command depends on command in Target 'FBReactNativeSpec': script phase “[CP-User] Generate Specs”
### To Reproduce

"react-native-square-in-app-payments": "^1.6.0",

Here is the pod file.

$RNFirebaseAsStaticFramework = true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'RNSquareTestApp' do
  use_frameworks!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'RNSquareTestAppTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end

**Environment:**

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 182.79 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 27.0.1, 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Screenshot
<img width="1440" alt="Screenshot 2021-08-17 at 9 23 47 PM" src="https://user-images.githubusercontent.com/46213090/129891119-c12be131-b409-455b-8aba-8082e52f6105.png">

**Comment by jguze** [comment]
Thanks for reporting this problem. 

Could you clarify the issue for me? In your title, you mentioned it wasn't working with xcode 12.4, but in your issue under environment, you mentioned you were using `Xcode: 11.3/11C29 - /usr/bin/xcodebuild`

This looks like a gap in our documentation, but in the latest versions of the IAP SDK, I believe xcode 12+ is required.

It's a bit difficult to understand how to repro your error. Do you have a minimal repro so that I can better understand the issue?

**Comment by saifuddinpopcornapps** [comment]
@jguze Thanks for looking into the issue.
**I was using xcode 12.4 with 11.3 command line tools. Now I checked with 12.4 command line tools still same issue**

### Latest Environment:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 2.01 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 27.0.1, 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
### Package.json:

{
  "name": "RNSquareTestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "build": "npx jetify && cd android && ./gradlew assembleRelease && cd ..",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "pod": "pod install --project-directory=ios",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "postinstall": "cat src/replacement/react-native-otp-input/index.js > node_modules/@twotalltotems/react-native-otp-input/dist/index.js && cat src/replacement/react-native-calendars/src.calendar.header.index.js > node_modules/react-native-calendars/src/calendar/header/index.js && cat src/replacement/react-native-calendars/src.calendar.index.js > node_modules/react-native-calendars/src/calendar/index.js && cat src/replacement/react-native-scrollable-tab-view/ScrollableTabBar.js > node_modules/react-native-scrollable-tab-view/ScrollableTabBar.js"
  },
  "dependencies": {
    "@alessiocancian/react-native-actionsheet": "^2.4.11",
    "@gregfrench/react-native-wheel-picker": "^1.2.14",
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-firebase/analytics": "^12.0.0",
    "@react-native-firebase/app": "^12.0.0",
    "@react-native-firebase/crashlytics": "^12.0.0",
    "@react-native-firebase/dynamic-links": "^12.3.0",
    "@react-native-picker/picker": "^1.16.1",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^0.21.1",
    "axios-auth-refresh": "^3.1.0",
    "babel-plugin-inline-import": "^3.0.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "^4.0.2",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-actions-sheet": "^0.4.9",
    "react-native-add-calendar-event": "^4.0.0",
    "react-native-animated-pagination-dots": "^0.1.72",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-autolink": "^4.0.0",
    "react-native-biometrics": "^2.1.4",
    "react-native-calendar-events": "^2.2.0",
    "react-native-calendars": "https://github.com/hithaprani-pop/react-native-calendars.git",
    "react-native-device-info": "^8.1.3",
    "react-native-elements": "^3.4.1",
    "react-native-email-link": "^1.11.3",
    "react-native-fast-image": "^8.3.4",
    "react-native-floating-label-input": "^1.3.9",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-accessory": "^0.1.15",
    "react-native-map-link": "^2.7.27",
    "react-native-maps": "^0.28.0",
    "react-native-orientation": "^3.1.3",
    "react-native-pager-view": "^5.2.1",
    "react-native-reanimated": "^2.1.0",
    "react-native-render-html": "^5.1.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.2.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.1",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-tab-view": "^3.0.1",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.1.1",
    "react-native-video-controls": "^2.8.1",
    "react-native-wallet": "^1.0.8",
    "react-native-webview": "^11.6.4",
    "use-async-effect": "^2.2.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.20",
    "@types/lodash": "^4.14.172",
    "@types/react-native": "^0.64.0",
    "@types/react-native-calendars": "^1.505.3",
    "@types/react-native-orientation": "^5.0.1",
    "@types/react-native-scrollable-tab-view": "^0.10.2",
    "@types/react-native-snap-carousel": "^3.8.3",
    "@types/react-native-video": "^5.0.5",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1",
    "reactotron-react-native": "^5.0.0",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

Please let me know if you need more info.

**Comment by jguze** [comment]
Thanks. Again, from the information you're sending, I am not sure exactly what is happening. Do you have a small sample app that you can share that can repro the issue?

As well, have you tried running our example application, found [here](https://github.com/square/in-app-payments-react-native-plugin/tree/master/react-native-in-app-payments-quickstart)? Do you get the same error as well?

**Comment by saifuddinpopcornapps** [comment]
@jguze Thanks for looking into the issue.
**I fixed the issue with the below podfile**

### Podfile

$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport=true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'RNSquareTestApp' do
  **use_frameworks! :linkage => :static**
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'RNSquareTestAppTests' do
    inherit! :complete
  end

  **post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end**
end

**Please check and let us know if you have any other solution.**

**Comment by jguze** [comment]
Hi @saifuddinpopcornapps, I'm glad you managed to resolve it.
From your solution, it seems like it was related to moreso towards the `FBReactNativeSpec`, and some odd build cycle. I don't have another solution off the top of my head here, and am not actually sure this was related to the Square plugin at all.

I'm happy you found a solution. I'll review our own podfile to see if there's anything we could do here, but will consider this issue closed.
