### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by dibelogrivaya** [square/in-app-payments-react-native-plugin#14]
**error: package org.jetbrains.annotations does not exist**

ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
        sqipVersion = "1.1.0"
    }

dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
}

distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

works only with distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

**Comment by hukid** [comment]
@dibelogrivaya , I hit the same issue when using  gradle-5.1.1-all.zip, this should be a bug in gradle-5.1.1, right now please downgrade to gradle-4.10.2-all.zip.
