### ISSUE TITLE
Error while running on Android, iOS works great

### ISSUE THREAD

**Issue by muhammadhurali** [square/in-app-payments-react-native-plugin#142]
### Describe the issue

Hi, I am facing an error when running on android, using "yarn android". Every time I get the error, screenshot attached:

### To Reproduce

Following are the configuration details:
package version: "react-native-square-in-app-payments": "^1.6.0",     "react-native": "0.62.2"
gradle-wrapper.properties: distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-bin.zip
project/build.gradle: {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29

     classpath("com.android.tools.build:gradle:3.5.2")
}

### Expected behavior

**Environment (please complete the following information):**

### Screenshots

<img width="1114" alt="Screenshot 2021-09-02 at 1 06 50 PM" src="https://user-images.githubusercontent.com/76680038/131806792-68df9302-735a-45ac-bf8c-80fe6a0e58aa.png">

### Additional context

Anyone who got it working on android, please provide your guidance. Maintainers, please share your comments here, that would be very helpful. Thank you !

**Comment by muhammadhurali** [comment]
Guys! Any leads?

**Comment by alikarani** [comment]
@muhammadhurali  I resolved this last Friday.
The issue was with my network. As it was adding some extra security due to which gradle couldn't sync properly I switched over my internet it worked well. And later I tested on the same internet with a vpn it also worked well.

As its resolved now. @muhammadhurali  please close this issue.
Thanks

**Comment by vishwajitshep0815** [comment]
Closing this issue as it was occurring due to network issues.
