### ISSUE TITLE
The minSdkVersion provided in the doc isn't 21 (Android)

### ISSUE THREAD

**Issue by YisusJe** [square/in-app-payments-react-native-plugin#155]
When i tried to build my app i have the following error: 
`uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.squareup.sdk.in-app-payments:buyer-verification:1.5.4] C:\Users\Jesus\.gradle\caches\transforms-2\files-2.1\1a4537152563a41bfcdf0bce1bf08b01\jetified-buyer-verification-1.5.4\AndroidManifest.xml as the library might be using APIs not available in 21`
I can't use minsdkVersion 24 because my app have other libraries that the maximum sdk uses is 21.
Is the documentantion outdated? or maybe is a library issue? Thanks

**Comment by CharmisG** [comment]
Buyer verification sdk will accept minsdkversion 24 so we need to use minsdkVersion 24 only.
