### ISSUE TITLE
Suddenly Unable to gradlew assembleRelease

### ISSUE THREAD

**Issue by n3rd253** [square/in-app-payments-react-native-plugin#159]
### Describe the issue
Have a pipeline in azure devops which is running on a hosted mac (Have tried 11.0 and 10.15)

Seems something has changed in the back since last Monday, but I can't figure out how to resolve, or what changed.

```
> Task :app:mergeReleaseNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseNativeLibs'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-java-res, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: /Users/runner/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Failed to transform '/Users/runner/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
```

I receive this above, with just standard gradlew assembleRelease.

This happens even on builds which were previously successful

### Expected behavior
Build completes smoothly

**Environment (please complete the following information):**
Azure Devops MSFT Hosted Agent.  MacOS 11 & 10.15.  Android

**Comment by vishwajitshep0815** [comment]
Hi @n3rd253, can you compare your gradle.properties file with the below one and check if it works for you?

https://github.com/square/in-app-payments-react-native-plugin/blob/master/react-native-in-app-payments-quickstart/android/gradle.properties

**Comment by vishwajitshep0815** [comment]
@n3rd253 did the above fix work for you?

**Comment by n3rd253** [comment]
@vishwajitshep0815  i'm sorry I just saw this response somehow.

No this does not work.  When I try to ignore the file, yes it builds.  But once app loads, it is unable to load CardEntryScreen due to below.
![Screenshot_20220422-114522_Market Feedback Agent](https://user-images.githubusercontent.com/20586952/164776250-a28a8055-8fae-4d92-9dff-cf2871f9d71a.jpg)

**Comment by n3rd253** [comment]
The response time on your developer support here is horrible at best.  Not even worth asking a question

**Comment by mirzahayat** [comment]
have you resolve this issue @n3rd253
