### ISSUE TITLE
React native - Xcode build failed.

### ISSUE THREAD

**Issue by luvnish19** [square/in-app-payments-react-native-plugin#163]
For Xcode 13.2:
After `npm i react-native-square-in-app-payments` I set `Deployment target` to `12.0` in `pod` and `Deployment Info` under General section as described in documentation.  
Pod installed successfully but when I try to build it. It give exceptions: 

<img width="434" alt="Screenshot 2022-03-20 at 12 11 56 PM" src="https://user-images.githubusercontent.com/15010312/159151340-5e3cd0e5-1df0-471a-9e35-fd572f389984.png">

Pod file:
<img width="677" alt="Screenshot 2022-03-20 at 12 13 11 PM" src="https://user-images.githubusercontent.com/15010312/159151449-ba12e600-1f43-4398-bd66-e04ab5b5756b.png">

I tried with best possible solutions like:
* pod deintegrate
* removing node_modules and install it again.

Hardware:
MacBook Pro M1 (2021)

Versions:
react-native : 0.67.2
react : 17.0.2
react-native-square-in-app-payments : 1.7.1

Please provide a solution for this. Thanks!

**Comment by CharmisG** [comment]
Resolved in latest code.
