### ISSUE TITLE
Click on delete while entering exp date of the card blocks the user from entering the details

### ISSUE THREAD

**Issue by dutradotdev** [square/in-app-payments-react-native-plugin#164]
### Describe the issue
While entering details of the expiry date of the card, if the user deletes the date and tries to re-enter again, the user cannot enter the details again.
Deleting the expiration date shouldn’t block the user from entering the details again

### To Reproduce
on Square integration enter card details
Enter the Expiry date and click on delete to delete entered date
Now enter the date again

### Expected behavior
The user should be able to enter the date

### Environment
  - platform: iOS
  - OS and version: iPhone 12
  - dev environment: macOS
  - In-App Payments Plugin version: 1.7.1

### Screenshots
https://user-images.githubusercontent.com/25035327/161770641-1b2baed9-53be-422b-b21d-1c5e1ff4c9d9.MP4

**Comment by CharmisG** [comment]
Resolved in latest update.
