### ISSUE TITLE
Apple pay in app clip error  -rn_apple_pay_not_supporte

### ISSUE THREAD

**Issue by janet-rivas** [square/in-app-payments-react-native-plugin#184]
### Describe the issue

A clear and concise description of what the issue is.

I'm developing app clip app and after I setup and run my app clip in the simulator works fine, however when I try to run it a physical device I got this error.
[javascript] 'APPLE PAY ', [Error: Something went wrong. Please contact the developer of this application and provide them with this error code: rn_apple_pay_not_supported] looks like I'm missing something. or I'm wondering if apple allows  using "in-app payments-react-native-plugin" in app clip 
  
  Here is the log:
  ```
022-10-06 15:29:12.099553-0400 mobileClip[24717:2066365] [Default] Error requesting calls from host: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.callkit.callcontrollerhost" UserInfo={NSDebugDescription=connection to service named com.apple.callkit.callcontrollerhost}
2022-10-06 15:29:13.119020-0400 mobileClip[24717:2066372] [javascript] 'APPLE PAY ', [Error: Something went wrong. Please contact the developer of this application and provide them with this error code: rn_apple_pay_not_supported]
  ```

### To Reproduce
  Steps to reproduce the issue.

  1. Create a new app clip target in existent react native  
  2. Initialize Apple Pay
  3. call `await SQIPApplePay.requestApplePayNonce` 

  Here the piece of code that reproduce the issue.
  ```javascript
   try {
      await SQIPApplePay.requestApplePayNonce(
        applePayConfig,
        onApplePayNonceRequestSuccess,
        onApplePayNonceRequestFailure,
        onApplePayEntryComplete,
      );
    } catch (error) {
      console.error('APPLE PAY ', error);
    }
  ```

### Expected behavior
The Apple Pay card opens.

**Environment (please complete the following information):**

System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 21.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.08.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
  IDEs:
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by tobischw** [comment]
Just checking the obvious; do you have Apple Pay successfully enabled and setup on your physical device?

Will follow up with the team on IAP SDK support in App Clip. I am unaware of any limitations there but will check.

**Comment by plinio-square** [comment]
At this point, we don't officially support App Clips. It's in our roadmap for the future, but we don't have a date planned for it yet.
