### ISSUE TITLE
Can't build android app with your plugin

### ISSUE THREAD

**Issue by attractfront** [square/in-app-payments-react-native-plugin#185]
has error 
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :square_in_app_payments > com.squareup.sdk.in-app-payments:buyer-verification:1.5.6 > com.squareup.sdk.in-app-payments:buyer-verification-internals:1.5.6 > com.nds.threeds:widget:1.3.9 > com.nds.threeds:core:1.3.9 > com.nds.threeds:threedssdk-release:1.10.7
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not GET 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > Read timed out
               
 my build.gradle
 buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.2'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.10'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

Flutter version 2.10.5
Dart version 2.16.2

Could you please help me with this issue?

**Comment by CharmisG** [comment]
@attractfront 
What is your distributionUrl version in gradle-wrapper.properties ?

**Comment by CharmisG** [comment]
Closing this issue but if you still find this problem please reopen this issue. Thank you.
