### ISSUE TITLE
Square Card Entry Form Toolbar Title Text Color

### ISSUE THREAD

**Issue by afanchamp** [square/in-app-payments-react-native-plugin#20]
Im able to change Toolbar but cannot change the Toolbar Title color from default (white) to black on any other color.

**Comment by rahamin1** [comment]
@afanchamp While waiting for a reply on this, can you show the result of the customizations that you have done and the modifications to the res files? In case you don't mind that I borrow some ideas...

**Comment by labmorales** [comment]
Any updates regarding this?

**Comment by hukid** [comment]
@afanchamp, is this for iOS or Android?
