### ISSUE TITLE
Expo Support

### ISSUE THREAD

**Issue by Carlwirkus** [square/in-app-payments-react-native-plugin#208]
### Describe the functionality you would like to see
Are there plans to support expo? I'm looking at creating an expo app for my startup and i'd love to be able to offer square payments via the reader. However I see that due to the native linking that this will likely not be possible. I'm just learning about expo but it seams like this could be possible via the new native module api.

**Comment by CharmisG** [comment]
@Carlwirkus 
Sorry but we don't officially support EXPO.

**Comment by danrivett** [comment]
Any update on this?

I would be really surprised if Expo isn't supported in 2024 given how much usage it has in the React Native space, and the develiper resources available to a company as large as Square is.

Has anyone been able to integrate this plugin into Expo yet?

We were going to spike this out following [Expo's guide](https://docs.expo.dev/workflow/using-libraries/#third-party-libraries) on building a development build with this dependency, but #193 seems to indicate an [Expo Config plugin](https://docs.expo.dev/config-plugins/introduction/) is required, but that PR has been given no attention by Square over the last 14 months it's been open 😖

**Comment by hmirza1** [comment]
Any movement on this? 🥲

**Comment by mgray88** [comment]
Until Square is willing to merge #193, I've extracted the functionality into a standalone plugin to make it easier to work with: https://github.com/TakeoutCentral/square-expo-plugin

Comments and contributions welcomed!
