### ISSUE TITLE
Error with Google Pay

### ISSUE THREAD

**Issue by AkbarBakhshi** [square/in-app-payments-react-native-plugin#216]
### Describe your question

I have set up Apple Pay, pay with a card, and Google Pay with this plugin on my app. Everything but Google Pay works fine. When I tap on the button that should open the Google Pay sheet, the spinner is displayed for a couple of seconds and then I get this message:

`Request failed. This Merchant is having trouble accepting your payment right now [OR_BIBED_11]`

![IMG_9334](https://github.com/square/in-app-payments-react-native-plugin/assets/46682991/b603461c-971e-4996-9cc1-03d111007774)

I have followed the steps in the ReadMe [here](https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/enable-googlepay.md). I don't see anything similar to adding Merchant ID for Apple Pay in the Google Pay docs so I am pretty sure I have done everything mentioned in the ReadMe. Are there any other steps that I need to take, maybe on the Google Pay side of things to fix this issue?

**Comment by AkbarBakhshi** [comment]
Do I need to complete this process (Request production access) for Google Pay? I don't see any mention of this in the documentation though.

https://developers.google.com/pay/api/android/guides/test-and-deploy/request-prod-access

**Comment by AkbarBakhshi** [comment]
Update: It seems like the `SQIPGooglePay.EnvironemtProduction` is the issue. The Google Pay modal sheet works fine with `SQIPGooglePay.EnvironmentTest`.

**Comment by CharmisG** [comment]
Thanks for the update, I'm closing the issue, but let us know if you face any issues.

**Comment by fka3** [comment]
You do need to request prod access; a public explanation is [here](https://stackoverflow.com/questions/76655117/or-bibed-11-error-in-google-pay-api-for-production-environment).

The test environment is for testing, so Google doesn't much care who is using that and it will always work.  Production, however, has higher scrutiny, and in particular the usual banking regulations mean Google needs to know who the money is going to.  (Among other uses, this is a check that it's _not_ going to known drug cartels, terrorists, etc., so pretty much any financial transfer is going to need some sort of registration.)

We should update our documentation to mention this; however, it's not "to use the Square SDK, you must..." but is instead "to use Google Pay _at all_, Square or not, you must..."
