### ISSUE TITLE
Application crash on IOS, giftcard number validation

### ISSUE THREAD

**Issue by hcruzpoppinpay** [square/in-app-payments-react-native-plugin#230]
Hi I have been working on the flow of adding a GiftCard but two problems have arisen:

1.- When I try to put an incorrect GiftCard number in Android the interface performs a correct validation of the entered GiftCard number, but when I enter it in IOS it does not perform any validation, it allows me to press the save button. The number I am using for the example is 1114 4444 4444 4444 4444.

2.- The second error occurs when I press the save button on IOS, the application crashed with exception: Invalid parameter not satisfying: cvv.

NSInternalInconsistencyException
Invalid parameter not satisfying: cvv

SquareInAppPaymentsSDK +0x0458d8 SQIPAlphanumericTextSanitizer
SquareInAppPaymentsSDK +0x038998 SQIPAssertMainThread
SquareInAppPaymentsSDK +0x03e2c4 SQIPAssertMainThread
Called from UIKitCore +0xe134a8 -[UIApplication sendAction:to:from:forEvent:]

### Expected behavior:
Validation between IOS and Android is consistent and  the IOS application not crash.

### Screenshots
![CleanShot 2024-03-15 at 11 01 18@2x](https://github.com/square/in-app-payments-react-native-plugin/assets/126699207/adf2d5eb-c2aa-4d5b-aa70-2d533f0d31c8)

**Comment by kirstiedownie** [comment]
Hi! We've added a fix for this which will be out in the next release.
