### ISSUE TITLE
Unexpected cfbundleexecutable key during appstore upload

### ISSUE THREAD

**Issue by gajjartejas** [square/in-app-payments-react-native-plugin#3]
I have followed all steps and successfully integrated plugin. When I upload ipa to app store using app loader I am getting the error:
![Screen Shot 2019-03-20 at 8 16 34 PM](https://user-images.githubusercontent.com/14052969/54694084-ae478b00-4b4d-11e9-85e4-15daaa5e8f49.png)

**Comment by hukid** [comment]
HI, @gajjartejas Thanks for reporting this issue! 

Can you try to manually remove `CFBundleExecutable` key from the RNSquareInAppPayments-Resources.bundle in your Xcode project and see if that works?
