### ISSUE TITLE
Unable to start after installation

### ISSUE THREAD

**Issue by liaokaime** [square/in-app-payments-react-native-plugin#34]
react-native version : 59.9
operating system : mojave 10.14.6
editor : webstorm 2019.03.EAP
react-native-square-in-app-payments : "^1.2.3",

I tried to follow the [documentation ](https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md) installation react-native-square-in-app-payments

1、Since I already had a react-native project, I skipped the [first step](https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md#step-1-create-a-react-native-project)

2、The command was copied directly and executed without hindrance
```
yarn add react-native-square-in-app-payments
react-native link react-native-square-in-app-payments
```

3、I chose [step 3b](https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md#step-3b-add-the-in-app-payments-sdk-to-your-ios-project-with-cocoapods)
3.1 touch Podfile
3.2 Edit Podfile as follows
```
platform :ios, '11.0' # set the platform version to 11.0

target 'feifan' do
  use_frameworks! # enalbe use_frameworks!

  # pod dependencies
  pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'
end
```

4、Since I only want to use it on ios, I skipped [step 4](https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md#step-4-configure-your-android-project)

5、I tried
```
react-native run-ios
```

6、The App did not start properly and an error was reported
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening feifan.xcworkspace

** BUILD FAILED **


The following build commands failed:
        CompileC /Users/liaokai/workspace/feifan/ios/build/feifan/Build/Intermediates.noindex/RNSquareInAppPayments.build/Debug-iphonesimulator/RNSquareInAppPayments.build/Objects-normal/x86_64/SQIPCardDetails+RNSQIPAdditions.o /Users/liaokai/workspace/feifan/node_modules/react-native-square-in-app-payments/ios/Converters/SQIPCardDetails+RNSQIPAdditions.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/liaokai/workspace/feifan/ios/build/feifan/Build/Intermediates.noindex/RNSquareInAppPayments.build/Debug-iphonesimulator/RNSquareInAppPayments.build/Objects-normal/x86_64/SQIPCard+RNSQIPAdditions.o /Users/liaokai/workspace/feifan/node_modules/react-native-square-in-app-payments/ios/Converters/SQIPCard+RNSQIPAdditions.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

**Comment by okenshields** [comment]
Hi,

Can you try run your app in xcode and see if it works? Also can you try some of the suggestions in this thread and see if any of those helps? https://github.com/facebook/react-native/issues/25240

**Comment by StephenJosey** [comment]
Hi @liaokaime were you able to get this running?

**Comment by StephenJosey** [comment]
Going to go ahead and close this due to no response. Please comment and I can reopen if you still are running into this.
