### ISSUE TITLE
Support RN 0.60+ autolinking

### ISSUE THREAD

**Issue by harleenarora** [square/in-app-payments-react-native-plugin#35]
New autolinking.

https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked

**Comment by StephenJosey** [comment]
We upgraded to react-native 0.61.5 recently. See this PR: https://github.com/square/in-app-payments-react-native-plugin/pull/43

**Comment by rahamin1** [comment]
Any idea what is the minimal version of react-native that can be used with the latest version of this repo?

**Comment by StephenJosey** [comment]
Hi @rahamin1 the minimum should be 0.57.8.
