### ISSUE TITLE
How to get the card nonce in react-native app?

### ISSUE THREAD

**Issue by harleenarora** [square/in-app-payments-react-native-plugin#36]
I have worked on the latest version of React-native version. 

**Requirement:** User fill the card details (card number, expire month, expire year and cvv), on submit I have get the card nonce using square up using application Id and location id of square up. After get the nonce, pass this nonce to my custom rest api. 

Please tell me how to get only card nonce using application id and location id of square.

**Comment by okenshields** [comment]
Hi Harleen,

You need to call startCardEntryFlow() to get a card nonce. See reference here: https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/reference.md#startcardentryflow
In the `onCardNonceRequestSuccess ` callback you can access the card nonce.

You can take a look at the example app as well.
A callback is passed here:
https://github.com/square/in-app-payments-react-native-plugin/blob/0f120d0c3e27b072e1af374df1862bbfcbad97bd/react-native-in-app-payments-quickstart/app/screens/HomeScreen.js#L304
In the callback method, you can access cardDetails.nonce: https://github.com/square/in-app-payments-react-native-plugin/blob/0f120d0c3e27b072e1af374df1862bbfcbad97bd/react-native-in-app-payments-quickstart/app/screens/HomeScreen.js#L197

**Comment by harleenarora** [comment]
How to pass the application_id and location_id ?

**Comment by okenshields** [comment]
> How to pass the application_id and location_id ?

Application id is set like this: https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md#step-2-initialize-the-in-app-payments-sdk

Or please take a look the example app: https://github.com/square/in-app-payments-react-native-plugin/blob/master/react-native-in-app-payments-quickstart/app/screens/HomeScreen.js#L89

Location id is not required for normal card entry. It's required for Google pay and SCA.

**Comment by StephenJosey** [comment]
@harleenarora were you able to get this working?

**Comment by StephenJosey** [comment]
Closing this for now. Please let us know if you still are having trouble, though!

**Comment by ank26oct** [comment]
facing same issue

**Comment by StephenJosey** [comment]
Hi @ank26oct which issue? Not able to get the nonce or how to set the application id and location id? What is happening exactly?
