### ISSUE TITLE
How to get the card nonce in react-native app?

### ISSUE THREAD

**Issue by harleenarora** [square/in-app-payments-react-native-plugin#37]
I have worked on the latest version of React-native version. 

Requirement: User fill the card details (card number, expire month, expire year and cvv), on submit I have get the card nonce using square up using application Id and location id of square up. After get the nonce, pass this nonce to my custom rest api.

**Comment by okenshields** [comment]
Hi Harleen,

This seems to be duplicate question? Please check comments in https://github.com/square/in-app-payments-react-native-plugin/issues/36

**Comment by StephenJosey** [comment]
Duplicate of https://github.com/square/in-app-payments-react-native-plugin/issues/36 as mentioned above. Closing this.
