### ISSUE TITLE
Could not find com.squareup.sdk.in-app-payments:buyer-verification:1.2.0.

### ISSUE THREAD

**Issue by harleenarora** [square/in-app-payments-react-native-plugin#38]
Could not find com.squareup.sdk.in-app-payments:buyer-verification:1.2.0.
Required by:
    project :react-native-square-in-app-payments

**Comment by okenshields** [comment]
It looks like your In App Payments SDK version is old. buyer-verification only exists in 1.3.0+. Can you upgrade and try again?

**Comment by dibelogrivaya** [comment]
Hi @okenshields 
I have the same problem when trying to update to the latest version:
`"react-native-square-in-app-payments": "^1.4.0",`
iOS - ok. Android - error:
`ERROR: Failed to resolve: com.squareup.sdk.in-app-payments:buyer-verification:1.1.0
Show in Project Structure dialog
Affected Modules: node_modules-react-native-square-in-app-payments-android-react-native-square-in-app-payments`
What am I doing wrong?

**Comment by rashidmakki** [comment]
open android/build.gradle and increase sqipVersion from "1.2.0" to "1.4.0"

android/build.gradle  file:
buildscript {
  ext {
      buildToolsVersion = "28.0.2"
      minSdkVersion = 21
      compileSdkVersion = 28
      targetSdkVersion = 27
      supportLibVersion = "28.0.0"
      sqipVersion = "1.4.0"
  }
  ...
}
