### ISSUE TITLE
How to downgrade the Android minSdkVersion=19 and Deployment target: iOS 9.1? 

### ISSUE THREAD

**Issue by harleenarora** [square/in-app-payments-react-native-plugin#44]
Hi, My project configuration are: 

Android: minSdkVersion=19
IOS: Deployment target: iOS 9.1

I can't change this, And this library is not support it. Please tell me how to downgrade this?

**Comment by StephenJosey** [comment]
There's no way to lower our requirements. The SDK requires Android minSdkVersion of 21, and iOS deployment target of 11 or greater.

**Comment by harleenarora** [comment]
My I-pad Version is : 9.3.6 and this app is not working on my I-pad. How to do this?

**Comment by StephenJosey** [comment]
Apologies for the delay, is this issue still occurring?

**Comment by StephenJosey** [comment]
Please reopen if you have further information!
