### ISSUE TITLE
How stable and mature is this plugin?

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#47]
I see that there are not to many users and followers.
Can you share your experience? Should I write Java code instead? (that will be used in my react native app).

Thank you.

**Comment by StephenJosey** [comment]
Hi @rahamin1 thanks for contacting us! This particular plugin is definitely stable and should be your go-to plugin if you intend on creating a mobile application using In-App Payments and writing in React Native. This plugin should be able to do everything that the native SDKs are able to do; please let us know if you believe that's not the case (or if you have any further questions/concerns).
