### ISSUE TITLE
saveButtonTextColor doesn't seem to affect anything

### ISSUE THREAD

**Issue by mrpritchett** [square/in-app-payments-react-native-plugin#49]
### Describe the issue
We are attempting to set the color of the Save Button in app payments for the "Pay" button for iOS. saveButtonTextColor is the object used to do so from the documentation. I've tried copying the documentation and adjusting values, writing it myself, and it won't take any of my changes. I've gotten all the other settings in that object to update things correctly, but text color doesn't seem to work.

### To Reproduce
```if (Platform.OS === 'ios') {
      await SQIPCardEntry.setIOSCardEntryTheme({
        saveButtonFont: {
            size: 30,
          },
          saveButtonTitle: 'Pay 💳 ',
          keyboardAppearance: 'Light',
          saveButtonTextColor: {
            r: 255,
            g: 0,
            b: 0,
            a: 1.0,
          },
      });
    }
```

### Expected behavior
The color should update where it says "Pay" to be the color I specify.
<img width="345" alt="Screen Shot 2020-01-10 at 11 37 31 AM" src="https://user-images.githubusercontent.com/3329081/72169710-a2a7a800-339d-11ea-8e68-991c3f5b95c0.png">

**Environment (please complete the following information):**
  - platform: iOS
  - OS and version: iOS11+
  - dev environment: MacOS
  - In-App Payments Plugin version: 1.3.0

 ```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 59.94 MB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

**Comment by mrpritchett** [comment]
More research, this is the initial state. The provided option sets the color once the data is filled in, but no the initial state.

**Comment by StephenJosey** [comment]
This is intended. According to the documentation: "The text color of the save button when enabled." (https://developer.squareup.com/docs/api/in-app-payment/ios/Classes/SQIPTheme.html#/c:objc(cs)SQIPTheme(py)saveButtonTextColor) Enabled, implying when it's clickable. There's no way to change the initial (disabled) text color at this time.

**Comment by mrpritchett** [comment]
I'd say that's not a great user experience, even if intended. Instead of closing this @StephenJosey, can we label this as a feature request and keep it open?

**Comment by StephenJosey** [comment]
Sure thing, of course!

**Comment by CharmisG** [comment]
Thank you for your feedback. We have shared the feedback with our team.
