### ISSUE TITLE
iOS Build Failed while linking.

### ISSUE THREAD

**Issue by ssaran791** [square/in-app-payments-react-native-plugin#51]
When i manually integrate square in app payment sdk without cocoapods, i am again and again getting following issue.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNSQIPBuyerVerification", referenced from:
      objc-class-ref in libRNSquareInAppPayments.a(RNSQIPCardEntry.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ssaran791** [comment]
![image](https://user-images.githubusercontent.com/13144195/72199348-d26bb400-3460-11ea-91ce-25408b840442.png)

**Comment by StephenJosey** [comment]
Hi @ssaran791 thanks for reporting. What is the output of "flutter doctor -v" in your terminal? Also, what version of flutter are you currently using?

**Comment by ssaran791** [comment]
step 3, after adding all the lib and setup. i am using, "Step 3a: Add the In-App Payments SDK to your iOS project without CocoaPods"

**Comment by StephenJosey** [comment]
Thanks for the info. I've escalated this to the appropriate team and will follow-up once I have more info.

**Comment by rahamin1** [comment]
Is there any update to this?

**Comment by mohsin-sq** [comment]
Hello,

Is this still an ongoing issue that you're facing?

**Comment by ssaran791** [comment]
@mohsin-sq i have migrated to CocoaPods and resolved this issue.
