### ISSUE TITLE
Quick start setup: executing the cURL command written into the debug output?

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#52]
[Step 5](https://github.com/square/in-app-payments-react-native-plugin/blob/master/react-native-in-app-payments-quickstart/README.md#step-5-use-the-nonce-in-a-curl-payment-command) of React Native Plugin for In-App Payments SDK Quick Start says: `Take a payment with the card nonce by executing the cURL command written into the debug output. of your development environment.`

I am running the sample app in a genymotion emulator (not from within Android studio). Debug is on and I tried to place an order with a credit card. The following messages are displayed on the console:
```
Running "RNInAppPaymentsQuickstart" with {"rootTag":11}
STARTING card entry
```

I probably misunderstood what you mean in `executing the cURL command written into the debug output`. Can you explain please?

**Comment by StephenJosey** [comment]
Hi @rahamin1, are you running from "react-native run-android"? If so, you can bring up the Developer Menu by using ⌘M on mac or Ctrl+M on Windows and Linux. In this menu, choose "Debug JS Remotely" which should open a Google Chrome tab. This tab will show the debug output, which will include the cURL command after you've typed a card and click buy.

**Comment by rahamin1** [comment]
Hi Stephen, I appreciate the prompt response!

As I wrote in my comment, debug is on and no cURL command is displayed. You can see console output in my comment. No cURL command there...

**Comment by StephenJosey** [comment]
Gotcha, sorry I missed that. In that case, what happens after you enter a card number? Are you getting that far?

**Comment by rahamin1** [comment]
Yes. Entered a card number, MM/YY, cvv and zip code and clicked buy.

**Comment by StephenJosey** [comment]
And do you see it spin for a moment - and receive a green check mark within the UI, followed by a modal pop-up saying that your card wasn't charged, but you can check your console etc?

**Comment by rahamin1** [comment]
When I click 'Pay' it does spin and then I get the following modal:
![image](https://user-images.githubusercontent.com/15701347/72543645-b9af3400-388e-11ea-9231-c049af425b4d.png)

**Comment by StephenJosey** [comment]
Are you using the sandbox application id from your Developer Dashboard when you've toggled "Sandbox", not your legacy sandbox application id?

**Comment by rahamin1** [comment]
That's it! Sorry :(

**Comment by rahamin1** [comment]
Using the app's sandbox application id ('sandbox-xxxx) I am not getting a cURL command in the console. If I am using my app's application id I do get a cURL command... Does this make sense?

**Comment by StephenJosey** [comment]
Right, based on the error above, it sounds like you were using a legacy sandbox application id. Legacy sandbox is not supported - so that error modal pops up. Did you confirm you're _not_ using the legacy sandbox application id, and it still is receiving that error?

**Comment by rahamin1** [comment]
I just checked again: I am using the Sandbox Application ID of my application, I get the error modal and the cURL command is not displayed. As I wrote, when I use the application ID I do get the cURL command...

What do you mean by 'the legacy sandbox application id'?

**Comment by StephenJosey** [comment]
Sorry for the delay here. In your developer dashboard: https://squareup.com/dashboard/apps/my-apps, after you choose your app, I just want to ensure you're copying the value from "Sandbox Application ID", and not choosing "View legacy sandbox credentials" as they're two different app ids. I just tested with my sandbox app id and it worked successfully.

**Comment by rahamin1** [comment]
To be sure, I reinstalled the app, following steps 1-4 from https://github.com/square/in-app-payments-react-native-plugin/tree/master/react-native-in-app-payments-quickstart#step-1-get-a-square-application-id-and-location-id.

I still don't see the cURL command in the console, and I am still getting the modal with the error.

Do you want me to copy here the Constants.js file, with the credentials that I am using?

**Comment by StephenJosey** [comment]
Hmmm, I just tested with those values and it worked successfully. Can you make sure you're using the latest version of the React-Native plugin (1.3.1)? I believe the early versions didn't support the new sandbox yet.

**Comment by rahamin1** [comment]
You can check [here ](https://github.com/square/in-app-payments-react-native-plugin/tree/master/react-native-in-app-payments-quickstart)what I am using...

**Comment by StephenJosey** [comment]
Hey @rahamin1 sorry for the delay here. I believe the `card_entry_sandbox_not_supported` error got returned on older versions of the SDK when you were using a sandbox application id and didn't use valid [sandbox test cards](https://developer.squareup.com/docs/testing/test-values#test-values).

I've tested with various cards, both valid and not, and have yet to receive the error that you have though. Could you test in iOS as well and see if you still get the same error?

**Comment by rahamin1** [comment]
Thanks Stephen! 

I wasn't aware of the sandbox test cards... Is it written anywhere in the setup instructions?

I tried with one of the cards, and the curl command is displayed in my console. I replaced the access token and the location id as required, and a transaction output is printed.

Am I supposed to see the transaction in the dashboard? Nothing is displayed there...

**Comment by StephenJosey** [comment]
Oh, awesome! So glad that was it, sorry that it took us so long to get there - thanks for your patience ;).

Regarding the transaction in the dashboard - if it's a sandbox transaction, you can only see it in your sandbox dashboard, which can be found on your [developer portal](https://developer.squareup.com/apps). You should see a section below your applications called "Sandbox Test Accounts". By default, you'll only have one (called "Default Test Account"), and you can click "Launch" and see the transaction there.

For more info on sandbox testing, see here: https://developer.squareup.com/docs/testing/sandbox

I'll leave this open for now; let me know if you aren't able to see the transaction or if you have more info.

**Comment by rahamin1** [comment]
I can see the transaction now. Thanks!

If you think that others may face the same issue I was facing then maybe you should add a comment that test cards should be used (here: https://github.com/square/in-app-payments-react-native-plugin/tree/master/react-native-in-app-payments-quickstart#step-5-use-the-nonce-in-a-curl-payment-command).

You were even more patient than I was. Thanks much! 
(I have a feeling that we will meet again here... :)
