### ISSUE TITLE
iOS, Attempt to present <UINavigationController: 0x7fb3b9b75000> on <RNNSideMenuController: 0x7fb3b9a17c00> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by sharma-archu** [square/in-app-payments-react-native-plugin#56]
I am getting this error inside xcode logs while opening square up add card model. Basically I am having a popup on screen to add new credit card after clicking on button I am calling "SQIPCardEntry.startCardEntryFlow()" square payment function and it's not appearing sqaure payment model. I am getting error inside xcode.

> Attempt to present <UINavigationController: 0x7fb3b9b75000> on <RNNSideMenuController: 0x7fb3b9a17c00> whose view is not in the window hierarchy!

> Warning: Attempt to present <UINavigationController: 0x7fdbdd27c600>  on <RNNSideMenuController: 0x7fdbdc91e000> which is already presenting <RCTModalHostViewController: 0x7fdbdeeb8780>

This works for  android but having an issue with iOS.  Its working fine without model on iOS, but creating problem when opening square up payment model on react native model(Only for iOS).

**Comment by StephenJosey** [comment]
Hi @sharma-archu this is expected behavior. If you want to display it from the modal then you either need to present on top of `RCTModalHostViewController` or close the `modal` view first. Please let me know if you still have questions though!

**Comment by Technickster** [comment]
@StephenJosey 
Is there a reason why it is like this? 

Any reason why we might not be allowed to present it from the current viewcontroller? It is a very simple change to the sdk.
