### ISSUE TITLE
Is there a way to check if setSquareApplicationId fails?

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#57]
I tried to put it inside a try/catch clause, but it doesn't report any error (I have used an invalid Application ID).

**Comment by StephenJosey** [comment]
This function won't fail with an invalid application id. However, when you try to actually generate a nonce, it would fail with an invalid application id. The setting of the application id doesn't do any checks for validity.

**Comment by rahamin1** [comment]
Thanks Stephen.

1. As you say, the call to `SQIPCardEntry.startCardEntryFlow` fails.
However, the error doesn't say that the application ID is wrong, but that 'the card entry is unauthorized' (see the screenshot below). Is that what it should say?

![image](https://user-images.githubusercontent.com/15701347/74846100-9ddcf900-5338-11ea-90b0-b849b34a7122.png)

2. IMHO, the error should be raised on the initialization of the App, and not when generating the nonce. I suggest to change this issue from a question to an enhancement. Does this make sense?

**Comment by StephenJosey** [comment]
Ah, yes, you're right I believe that is the real error. I've updated this to be an enhancement, it does make sense. Thank you for the feedback!

**Comment by rahamin1** [comment]
Thanks Stephen.
Regarding the error: I would expect something like "Invalid application id" and not "card unauthorized" which I understand as an problematic card number..

If you do, then we have an (1) enhancement for reporting the error when setSquareApplicationId  is called, and a (2) bug for the invalid error code. If (1) is done, then (2) is not needed. If (1) is not done, then (2) needs to be fixed. .

**Comment by CharmisG** [comment]
Thank you for your feedback. We have shared the feedback with our team.
