### ISSUE TITLE
Can we get the last 4 digits of credit cards?

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#59]
Since the API is processing the user's credit card details, these details are not exposed to the app.

Is it possible to get at least the last 4 digits of the card?

This is needed, for example, when the user wants to save a card and use to in future payments. I would like to display the last 4 digits so that the user knows which card she is using. If the user is using more than a single card, we cannot do without it.

**Comment by StephenJosey** [comment]
Yes, it is possible via many ways. In the In-App Payments SDK itself, you'll receive `cardDetails` in the [cardEntryNonceRequestSuccessCallback](https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/reference.md#cardentrynoncerequestsuccesscallback) callback, which has a `nonce` and `card` attribute, and the `card` object has several fields such as `lastFourDigits`.

You'll also be able to see it at a later time, if the payment was processed, via the [Payments API](https://developer.squareup.com/reference/square/payments-api/get-payment#response__property-payment) in the `card_details` field, or the [Customers API](https://developer.squareup.com/reference/square/customers-api/retrieve-customer#response__property-customer) in the `cards` array field (if you choose to save the card on file).
