### ISSUE TITLE
Duplicate class conflict with react-native-code-push

### ISSUE THREAD

**Issue by DChiuch** [square/in-app-payments-react-native-plugin#62]
I'm getting these errors when I have both react-native-square-in-app-payments and react-native-code-push installed:

`Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.nimbusds.jose.JWEObject found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.JWEObject$State found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.JWSObject found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.JWSObject$State found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.Payload found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.Payload$Origin found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.Requirement found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.crypto.AESEncrypter$AlgFamily found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)
  Duplicate class com.nimbusds.jose.jwk.KeyOperation found in modules jetified-threedssdk-release-1.1.17-runtime.jar (com.nds.threeds:threedssdk-release:1.1.17) and nimbus-jose-jwt-5.1.jar (com.nimbusds:nimbus-jose-jwt:5.1)`

**Comment by DChiuch** [comment]
This appears to work as a temporary measure:

In `./node_modules/react-native-square-in-app-payments/android/build.gradle`

Replace

`implementation "com.squareup.sdk.in-app-payments:buyer-verification:$sqipVersion"`

With

```
compile ("com.squareup.sdk.in-app-payments:buyer-verification:$sqipVersion") {
    exclude group: 'com.nds.threeds', module: 'threedssdk-release'
}
```

**Comment by cnuss** [comment]
Any fixes found for this outside of changing the `build.gradle` file?

**Comment by ac130kz** [comment]
Had the exact same problem with https://github.com/DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter. Solved it with:

```
configurations {
    implementation {
        exclude group: 'com.nds.threeds', module: 'threedssdk-release'
    }
}
```

**Comment by DChiuch** [comment]
> Had the exact same problem with https://github.com/DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter. Solved it with:
> 
> ```
> configurations {
>     implementation {
>         exclude group: 'com.nds.threeds', module: 'threedssdk-release'
>     }
> }
> ```

That works for me.

**Comment by NguyenLuongVinh** [comment]
> Had the exact same problem with https://github.com/DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter. Solved it with:
> 
> ```
> configurations {
>     implementation {
>         exclude group: 'com.nds.threeds', module: 'threedssdk-release'
>     }
> }
> ```

Thanks you, that work for me :D

**Comment by LukhiKartik** [comment]
I have added below code in build.gradle and i am able to create build but app get crash on save button when using buyer verification flow.  https://github.com/square/in-app-payments-react-native-plugin/issues/137

configurations {
    implementation {
        exclude group: 'com.nds.threeds', module: 'threedssdk-release'
    }
}

**Comment by drdpedroso** [comment]
I'm still seeing this error even with the above solutions. My RN version is `0.63.4`and `"react-native-square-in-app-payments": "^1.6.0"`.

Any other possible solution for this?

**Comment by Balthazar33** [comment]
> 

Hi,

Could you please specify where you have added this?
