### ISSUE TITLE
Is it possible to specify the zipcode format of the in the Payment Entry Form

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#63]
In https://developer.squareup.com/docs/in-app-payments-sdk/cookbook/customize-payment-form,
I would like to set the zipcode field to accept only 5 digits.

Is this possible? Any other formatting options for this field?

**Comment by StephenJosey** [comment]
That is not currently possible, unfortunately.

**Comment by CharmisG** [comment]
Thank you for your feedback. We have shared the feedback with our team.
