### ISSUE TITLE
Square Gift crad payment incorporation into WooCommerce 

### ISSUE THREAD

**Issue by jcromp60** [square/in-app-payments-react-native-plugin#65]

**Comment by StephenJosey** [comment]
Hey @jcromp60 I think this is the wrong place to submit this feature request. WooCommerce handles their own integration, Square didn't create or maintain it, so you'll want to raise this feature request with them. Square already allows Square gift card payments via the Square Payment Form (https://developer.squareup.com/docs/payment-form/gift-cards/intro) so it'd be up to WooCommerce to just update to use it.
