### ISSUE TITLE
iOS: various issues in setup (NativeEventEmitter: native module cannot be null)

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#66]
_Keywords of issues discussed in this thread:  podfile definition nativeevent native event emitter Module SquareInAppPaymentsSDK not found._

### Here is my podfile before changing it.

Can you explain how to modify it (It is written in https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md#step-3b-add-the-in-app-payments-sdk-to-your-ios-project-with-cocoapods) but I failed :(

```
# platform :ios, '11.0'

target 'myproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myproject

  target 'myprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myproject-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myproject-tvOS

  target 'myproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by StephenJosey** [comment]
`Podfile` is the name of the file. You can open it with pretty much any text editor to confirm the settings.

**Comment by rahamin1** [comment]
Well, to minimize my shame, I have am trying the following, I will see if it is working:

```
# platform :ios, '11.0'

target 'myproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myproject
   pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'

end

```

**Comment by StephenJosey** [comment]
Ah, I see, my apologies. What is the error that you're receiving? I can try to dig one up shortly if needed.

**Comment by rahamin1** [comment]
Sure, no problem.

What I have written seems fine... 
I was doing this differently before. I was bored, so I gave it another try.

Here is the output:
```
Analyzing dependencies
Downloading dependencies
Installing RNSquareInAppPayments (1.3.0)
Installing React (0.11.0)


Installing SquareBuyerVerificationSDK (1.3.0)
Installing SquareInAppPaymentsSDK (1.3.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.

[!] React has been deprecated
```

**Comment by rahamin1** [comment]
Update: the build fails (I thought before that this is another problem, but when I deleted the new line (`pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'`), the errors are gone.

### In the metro bundler window:

```
Loading dependency graph...(node:43888) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: /Users/user172615/Documents/myproject/ios/Pods/React/package.json collides with /Users/user172615/Documents/myproject/node_modules/react-native/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/user172615/Documents/myproject/node_modules/jest-haste-map/build/index.js:569:17)
```

### And, in the Xcode's build output:

`Module 'SquareInAppPaymentsSDK' not found`

**Comment by StephenJosey** [comment]
Have you tried running using the command line instead (`react-native run-ios`)? Does it give the same error? Seems strange that it says it installed it, but then it's not found.

**Comment by rahamin1** [comment]
Yes, it does:

`/node_modules/react-native-square-in-app-payments/ios/Converters/SQIPCardDetails+RNSQIPAdditions.h:17:9: module 'SquareInAppPaymentsSDK' not found`

**Comment by rahamin1** [comment]
Please leave this issue open. I am trying the installation again, will post results here.

**Comment by rahamin1** [comment]
I am back here now (since the Reader error was gone): getting  in the Xcode's build output:
Module 'SquareInAppPaymentsSDK' not found.

**Comment by StephenJosey** [comment]
Just to confirm, did you run the Step 2 install and linking of the plugin?
```
yarn add react-native-square-in-app-payments
react-native link react-native-square-in-app-payments
```
Also, is the `Podfile` listed under the `ios` directory, and not the root directory of your react native project?

**Comment by rahamin1** [comment]
To make sure, I just did again. Rebuild. Same error.

**Comment by rahamin1** [comment]
Any idea about what else I can check?

**Comment by rahamin1** [comment]
I did everything again from the beginning, making sure that I am doing everything step by step. Same error...
Any idea about what else I can check?

Stephen, if you don't have an idea, how about that I give you access to my Mac, to try and fix it for me? :)

**Comment by rahamin1** [comment]
Since I didn't have any more ideas, I decided to create a new react-native project and add the plugin (or package, whatever you call it). Perhaps the following can explain the problem I am having?

### When running `react-native link react-native-square-in-app-payments` in this new project, the output is:  

**#react-native link react-native-square-in-app-payments**
```
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Linking "react-native-square-in-app-payments" iOS dependency
info iOS module "react-native-square-in-app-payments" has been successfully linked
info Linking "react-native-square-in-app-payments" Android dependency
info Android module "react-native-square-in-app-payments" has been successfully linked

```

### And when running in my project (for which linking on android has been done before), I only get:
**#react-native link react-native-square-in-app-payments**
```
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

**Comment by rahamin1** [comment]
I am continuing to post here, hoping that anybody reading this will get a clue and help me find a solution to my problem (in other words, helping you to help me ;)

I am not sure if the difference in output of `react-native link` (see previous comment) means anything. 
Anyway, according to https://reactnative.dev/docs/linking-libraries-ios#manual-linking there are 3 steps performed by `react-native link`, so I checked if all 3 have been done by `react-native link` (well, the 3rd step is optional, I don't know if it is required).

### Looking at the `header search paths` that is modified in step 3, I found that it doesn't look right:

![Header Search Paths 1](https://user-images.githubusercontent.com/15701347/81313898-23975780-9091-11ea-8394-190f0cea2d0d.png)

### So I modified it to look as following:

![Header Search Paths 2](https://user-images.githubusercontent.com/15701347/81313936-2eea8300-9091-11ea-8a49-129b22ef4139.png)

### But I still get the error... :(

**Comment by rahamin1** [comment]
One more thing:
Step 2 in https://reactnative.dev/docs/linking-libraries-ios#manual-linking is modifying the
`Build Phases -> Link binary with libraries` list.

Looking at this list, I see two entries that belong to the library. Is it what should be there?

![image](https://user-images.githubusercontent.com/15701347/81314980-67d72780-9092-11ea-8ca5-71aa367c918b.png)

**Comment by StephenJosey** [comment]
Apologies for the delay here. Would you be able to provide access to your project (via a Github repo or something similar) so I could take a look?

**Comment by rahamin1** [comment]
Can you send me an email? yossi.glass@gmail.com

**Comment by rahamin1** [comment]
It is impossible right now, thanks for suggesting that.

Trying to find clue to why I get the error: when the following error is issued, where is Xcode supposed to find the library? By looking in 'Link binary with libraries'? Anywhere else?

![image](https://user-images.githubusercontent.com/15701347/81426533-0088a880-9162-11ea-94d2-ab9f15d59975.png)

**Comment by rahamin1** [comment]
One more thing that comes to mind: did anybody build an iOS version with RN 0.59.9?

**Comment by StephenJosey** [comment]
Following up here, someone is having a similar issue on Flutter. I don't believe we've ever tested both In-App Payments SDK and ReaderSDK on the same device. Could you explain your use-case on why you're trying to use both? In-App Payments SDK is meant as a customer-facing, buy online application, while ReaderSDK is meant as a merchant-facing, buy in-person application.

**Comment by rahamin1** [comment]
The application is handling both scenarios.
But I am not sure that the problem is in using both. 

My feeling is that the problem happens because I am taking an app that was built on android (with an iOS folder that was generated by `react-native init` on android and try to run it on iOS).

I am trying now to create a new app on iOS, and bring my files from android. I will update when I have results.

**Comment by rahamin1** [comment]
I created a new RN repo with the same version I am using (0.59.9) and then added my files (added the package without cocoapods. When I added it with cocoapods it had the same problem reported in the title of this issue).

Then I added my files.

Now, when running the app, I am getting a red screen (I am attaching the text below the image):

![image](https://user-images.githubusercontent.com/15701347/82139691-7cee4c00-9832-11ea-95d8-87a819d71948.png)

### This is the text copied from the red screen:
```
Native module cannot be null.

new NativeEventEmitter
    NativeEventEmitter.js:36:6
<unknown>
    CardEntry.js:52:25
loadModuleImplementation
    require.js:330:4
guardedLoadModule
    require.js:205:11
metroRequire
    require.js:125:6
<unknown>
    index.js:17
loadModuleImplementation
    require.js:330:4
guardedLoadModule
    require.js:205:11
metroRequire
    require.js:125:6
```

**Comment by StephenJosey** [comment]
Hey @rahamin1 thanks for providing the sample repo. I am seeing the same as you are thus far. Will try a few things and escalate if needed. I'll follow up once I have more info.

**Comment by rahamin1** [comment]
That's great! Looking forward... :)

**Comment by StephenJosey** [comment]
I've escalated this and will follow up once I have more information from the team.

**Comment by rahamin1** [comment]
Thanks much!
I hope that somebody will find a solution soon, because we rely on it...

Best regards
Yossi

**Comment by rahamin1** [comment]
I tried to migrate to react-native 062.2. Same error.
If we don't manage to solve this, we will have to evaluate stripe or something comparable. I hate to do that, but I don't see any other way...
please make another effort.

**Comment by rahamin1** [comment]
I upgraded to RN 0.62.2 and error is gone.
Thanks again, Stephen!
