### ISSUE TITLE
Apple Pay Documentation Missing

### ISSUE THREAD

**Issue by QuintonC** [square/in-app-payments-react-native-plugin#69]
### Describe the change you would like to see

https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/enable-applepay.md#

Anything past step 3 is missing from the documentation.

### How would the suggested change make the documentation more useful?

Links for step 4 and step 5 are present at the top of the readme, however they are not in the documentation at all. It is not clear how to move forward after receiving the nonce.

### Additional context

I am reading the documentation directly from GitHub.

**Comment by StephenJosey** [comment]
Thanks for the feedback, not sure what happened there. I'll share this with the team!
