### ISSUE TITLE
Is sandbox support?

### ISSUE THREAD

**Issue by x956606865** [square/in-app-payments-react-native-plugin#74]
I got an error when using the sandbox application ID to fire "setIOSCardEntryTheme" and input my card info.
But if I use the production application ID, it will be work fine, and get a nonce.
So does this package support sandbox ??

**Comment by StephenJosey** [comment]
Hi @x956606865 what error are you seeing? Sandbox is supported, please make sure you're using the latest versions of the SDKs as well as not using the legacy sandbox credentials.

**Comment by x956606865** [comment]
oh....sorry, it works now, maybe it is my network issue? thanks to your help
