### ISSUE TITLE
Using with React Native Navigation

### ISSUE THREAD

**Issue by kyledmellander** [square/in-app-payments-react-native-plugin#8]
When using react-native-navigation as your navigation library (which uses native navigation components for IOS / android), using a custom back-button icon causes the back button to not appear when entering a card.

Notes: It does respect changes that you make to the default back button color (ours is black rather than the default blue) but doesn't work with icon changes. The api doesn't allow you to customize the screen title (ie with a custom component like react-native-navigation lets you). It would be nice if this didn't push a new screen at all (and wasn't coupled with navigation), but instead was simply a native component that you could put into a screen - that way you could overwrite navigation options as you saw fit.

React Native Version: 0.57.5
React Native Navigation Version: 2.1.3
Platform: IOS * (Haven't tested on android)

**Comment by StephenJosey** [comment]
Thanks for reaching out.

Unfortunately, using a custom back button icon isn't currently available for the In-App Payments SDK.

We are constantly improving the product based on feedback like this, so I'll be sure to share your thoughts with the API team.
