### ISSUE TITLE
iOS Release builds fail with XCode 12

### ISSUE THREAD

**Issue by tavour-frank** [square/in-app-payments-react-native-plugin#84]
### Describe the issue
Attempting to do a release build with XCode 12 fails with error:

  ```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/frank/Desktop/in-app-payments-react-native-plugin/react-native-in-app-payments-quickstart/ios/Pods/SquareBuyerVerificationSDK/SquareInAppPaymentsSDKs.framework/SquareBuyerVerificationSDK.framework/SquareBuyerVerificationSDK' for architecture arm64
  ```

Downgrading to XCode 11.7 via xcode-select succeeds on the same build invocation.

### To Reproduce

  1. Clone the quickstart app
  2. Install packages & pods
  3. Attempt release build

  ```
 xcodebuild -workspace ios/RNInAppPaymentsQuickstart.xcworkspace/ -scheme RNInAppPaymentsQuickstart -configuration Release -sdk iphonesimulator -derivedDataPath ios/build
  ```

### Expected behavior
Build should succeed regardless of using XCode 11.7 or XCode 12

### Additional context
First noticed in my own app and was able to reproduce with the quickstart app. Downgrading to XCode 11.7 consistently results in a successful build, but XCode 12 consistently fails.

Relevant output from `xcodebuild -version`
 Successfully builds on:
```
Xcode 11.7
Build version 11E801a
```

Fails to build on:
```
Xcode 12.0.1
Build version 12A7300
```

**Comment by StephenJosey** [comment]
Apologies for the delay. Please try a newer iOS In-App Payments version, and let me know if you continue to experience the same issue.

**Comment by vishwajitshep0815** [comment]
The build is working fine with the updates and fixes for XCode13. So, closing this bug.
