### ISSUE TITLE
Android Build Error 401 Unauthorized

### ISSUE THREAD

**Issue by thedrew12** [square/in-app-payments-react-native-plugin#91]
I'm running into this error when building the project:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.squareup.sdk.in-app-payments:card-entry:1.4.0.
     Required by:
         project :app > project :react-native-square-in-app-payments
      > Could not resolve com.squareup.sdk.in-app-payments:card-entry:1.4.0.
         > Could not get resource 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/card-entry/1.4.0/card-entry-1.4.0.pom'.
            > Could not GET 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/card-entry/1.4.0/card-entry-1.4.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.squareup.sdk.in-app-payments:google-pay:1.4.0.
     Required by:
         project :app > project :react-native-square-in-app-payments
      > Could not resolve com.squareup.sdk.in-app-payments:google-pay:1.4.0.
         > Could not get resource 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/google-pay/1.4.0/google-pay-1.4.0.pom'.
            > Could not GET 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/google-pay/1.4.0/google-pay-1.4.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.squareup.sdk.in-app-payments:buyer-verification:1.4.0.
     Required by:
         project :app > project :react-native-square-in-app-payments
      > Could not resolve com.squareup.sdk.in-app-payments:buyer-verification:1.4.0.
         > Could not get resource 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/buyer-verification/1.4.0/buyer-verification-1.4.0.pom'.
            > Could not GET 'https://sdk.squareup.com/public/android/com/squareup/sdk/in-app-payments/buyer-verification/1.4.0/buyer-verification-1.4.0.pom'. Received status code 401 from server: Unauthorized
 ```
 
Starting a new project and running into this error with the latest version. It is trying to call an API without any creds and I can't seem to find any documentation on this on why it would be happening.

**Comment by StephenJosey** [comment]
Thanks for reporting. We were having an internal issue on our side; please try again this should be working correctly now!

**Comment by nik-ust** [comment]
have the same issue now
`> Could not find com.squareup.sdk.in-app-payments:card-entry:1.6.6.
     Searched in the following locations:
       - file:/Users/nikitasubbotin/Projects/tea2go-app/node_modules/@notifee/react-native/android/libs/com/squareup/sdk/in-app-payments/card-entry/1.6.6/card-entry-1.6.6.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/squareup/sdk/in-app-payments/card-entry/1.6.6/card-entry-1.6.6.pom
       - https://repo.maven.apache.org/maven2/com/squareup/sdk/in-app-payments/card-entry/1.6.6/card-entry-1.6.6.pom
       - file:/Users/nikitasubbotin/Projects/tea2go-app/node_modules/jsc-android/dist/com/squareup/sdk/in-app-payments/card-entry/1.6.6/card-entry-1.6.6.pom
       - https://dl.google.com/dl/android/maven2/com/squareup/sdk/in-app-payments/card-entry/1.6.6/card-entry-1.6.6.pom
       - https://www.jitpack.io/com/squareup/sdk/in-app-payments/card-entry/1.6.6/card-entry-1.6.6.pom
     Required by:
         project :app > project :react-native-square-in-app-payments
   > Could not find com.squareup.sdk.in-app-payments:google-pay:1.6.6.
     Searched in the following locations:
       - file:/Users/nikitasubbotin/Projects/tea2go-app/node_modules/@notifee/react-native/android/libs/com/squareup/sdk/in-app-payments/google-pay/1.6.6/google-pay-1.6.6.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/squareup/sdk/in-app-payments/google-pay/1.6.6/google-pay-1.6.6.pom
       - https://repo.maven.apache.org/maven2/com/squareup/sdk/in-app-payments/google-pay/1.6.6/google-pay-1.6.6.pom
       - file:/Users/nikitasubbotin/Projects/tea2go-app/node_modules/jsc-android/dist/com/squareup/sdk/in-app-payments/google-pay/1.6.6/google-pay-1.6.6.pom
       - https://dl.google.com/dl/android/maven2/com/squareup/sdk/in-app-payments/google-pay/1.6.6/google-pay-1.6.6.pom
       - https://www.jitpack.io/com/squareup/sdk/in-app-payments/google-pay/1.6.6/google-pay-1.6.6.pom
     Required by:
         project :app > project :react-native-square-in-app-payments
   > Could not find com.squareup.sdk.in-app-payments:buyer-verification:1.6.6.
     Searched in the following locations:
       - file:/Users/nikitasubbotin/Projects/tea2go-app/node_modules/@notifee/react-native/android/libs/com/squareup/sdk/in-app-payments/buyer-verification/1.6.6/buyer-verification-1.6.6.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/squareup/sdk/in-app-payments/buyer-verification/1.6.6/buyer-verification-1.6.6.pom
       - https://repo.maven.apache.org/maven2/com/squareup/sdk/in-app-payments/buyer-verification/1.6.6/buyer-verification-1.6.6.pom
       - file:/Users/nikitasubbotin/Projects/tea2go-app/node_modules/jsc-android/dist/com/squareup/sdk/in-app-payments/buyer-verification/1.6.6/buyer-verification-1.6.6.pom
       - https://dl.google.com/dl/android/maven2/com/squareup/sdk/in-app-payments/buyer-verification/1.6.6/buyer-verification-1.6.6.pom
       - https://www.jitpack.io/com/squareup/sdk/in-app-payments/buyer-verification/1.6.6/buyer-verification-1.6.6.pom
     Required by:
         project :app > project :react-native-square-in-app-payments`

**Comment by Armaxis** [comment]
Based on the error message, Gradle is trying to find the artifacts on `mavenCentral()`, `jitpack()` and `google()` repositories, while in reality they are hosted on Square's server.
We specify the repository in [android/build.gradle](https://github.com/square/in-app-payments-react-native-plugin/blob/62155ba4ce5f34500d8f231d9e437f5916674fb8/android/build.gradle#L35), but maybe it's accidentally overridden by your app's configuration?
Make sure you're listing our maven repo in your build.gradle script
```
repositories {
    ...
    maven {
        url 'https://sdk.squareup.com/public/android'
    }
}
```

**Comment by nik-ust** [comment]
it works! thank you @Armaxis !
