### ISSUE TITLE
iOS installation instructions are outdated

### ISSUE THREAD

**Issue by darajava** [square/in-app-payments-react-native-plugin#93]
### Describe the change you would like to see
I am new to React Native and even newer to iOS so please bear with me.

I tried following the steps you give in this video:

https://www.youtube.com/watch?v=PoVuik5jqxI&ab_channel=SquareDeveloper

The video is great, but I couldn't do the last step in XCode. (The libraries folder was completely empty for me). The project would not build. However, I started from scratch and did nothing except for `react-native link` (and maybe `pod install`) and it worked without issue. I believe this manual linking is no longer needed in RN > v0.6

### How would the suggested change make the documentation more useful?

It would save people on newer versions of React Native hours of time and guessing.

**Comment by StephenJosey** [comment]
I think that part is only if you're installing without Cocoa Pods. You can see the difference between with and without Cocoa Pods here: https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md#step-3a-add-the-in-app-payments-sdk-to-your-ios-project-without-cocoapods (which only the non Cocoa Pods ask you to drag the resources bundle from your Libraries).
