### ISSUE TITLE
Cardholder name in the payment form

### ISSUE THREAD

**Issue by sandrok1609** [square/in-app-payments-react-native-plugin#94]
Is there a way to enable a cardholder name input in the form? I looked at the cardEntryConfig and as far as I know you can only require the user to enter the zip code

**Comment by StephenJosey** [comment]
The In-App Payments SDK is solely around card information. If you want to collect additional customer information such as the cardholder's name, you'll need to implement that yourself. You can also pass that data to the `CreateCustomer` API to actually create the customer, if you choose, but that is outside of this plugin.
