### ISSUE TITLE
Adding SCA support for a card-on-file ID for the buyer's payment card stored with Square

### ISSUE THREAD

**Issue by azmicirit** [square/in-app-payments-react-native-plugin#96]
The official Square react native library has no support to take payments with saved cards that requires 3D secure payments (SCA). Because both of Android and iOS codes are not able to change the Payment Source ID rather than card details(nonce) from Card Entry Flow.

`String paymentSourceId = cardResult.getNonce();`
[https://github.com/azmicirit/in-app-payments-react-native-plugin/blob/b565bcfb0026266d703b5b4b87ed1f8850d9f1f4/android/src/main/java/sqip/react/CardEntryModule.java#L90](url)

`NSString *paymentSourceId = self.cardDetails.nonce;`
[https://github.com/azmicirit/in-app-payments-react-native-plugin/blob/b565bcfb0026266d703b5b4b87ed1f8850d9f1f4/ios/RNSQIPCardEntry.m#L402](url)

I forked this repository and added new method into CardEntry class to able to change paymentSourceId as card.id. It is also mentioned here [https://developer.squareup.com/docs/in-app-payments-sdk/verify-buyer#step-2-prepare-for-the-verification-flow](url)

> Payment source ID. This ID can be the nonce returned by the CardEntry activity or a card-on-file ID for the buyer's payment card stored with Square.

For now, we can take 3d secure payments(SCA) with customers' saved cards in Sandbox mode. I just wonder can we merge and test these updated codes from forked repository.

[https://github.com/azmicirit/in-app-payments-react-native-plugin](url)

**Comment by StephenJosey** [comment]
Thanks for sharing this. We are looking into this.

**Comment by vishwajitshep0815** [comment]
Closing this, as it has been addressed in the latest release.
