### ISSUE TITLE
Can this autofill card details?

### ISSUE THREAD

**Issue by darajava** [square/in-app-payments-react-native-plugin#97]
If I have card details saved to my device, can this plugin autofill?

**Comment by StephenJosey** [comment]
You would be able to use google/apple pay, but I don't think mobile devices typically allow autofilling in a mobile application, unless I'm misunderstanding. So, no to autofilling right now.

**Comment by darajava** [comment]
![image](https://user-images.githubusercontent.com/5908229/150400915-f517537c-dca1-4b44-970b-52a364ba326a.png)
@StephenJosey it seems to be possible in the Uber Eats app on Android at least.
